[package]
name = "jodelrs"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
hmac = "0.12.1"
sha1 = "0.10.6"
hex = "0.4.3"
http = "1.3.1"
chrono = "0.4.41"
url = "2.5.4"
